# Generated by Django 3.2.12 on 2023-02-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Compound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("formula", models.CharField(max_length=100)),
                ("iupac", models.CharField(max_length=200)),
                ("cas", models.CharField(max_length=30)),
                ("tags", models.CharField(max_length=200)),
                ("place", models.CharField(max_length=10)),
            ],
        ),
    ]
