# Generated by Django 4.1.7 on 2023-02-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Compound",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("formula", models.CharField(max_length=100)),
                ("iupac", models.CharField(blank=True, max_length=200, null=True)),
                ("cas", models.CharField(blank=True, max_length=30, null=True)),
                ("tags", models.CharField(blank=True, max_length=200, null=True)),
                ("shelf", models.CharField(max_length=10)),
                ("rack", models.CharField(max_length=10)),
            ],
        ),
    ]
