# Generated by Django 4.1.7 on 2023-02-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0002_rename_place_compound_rack_compound_shelf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compound",
            name="cas",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="compound",
            name="iupac",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="compound",
            name="tags",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
